"use client";
import { useActiveProjectState } from "@/hooks/useActiveProject";
import { useOfficeStore } from "@/store/useOfficeStore";
import { sendOffice } from "@/hooks/useOfficeSocket";
import { useWhenOfficeConnected } from "@/hooks/useWhenOfficeConnected";
import { useOfficeI18n } from "@/i18n/officeI18n";
const send=sendOffice
export function ProductionHardeningPanel(){
  const {t}=useOfficeI18n();
  const state=useActiveProjectState(),recovery=useOfficeStore(s=>s.recovery),audit=useOfficeStore(s=>s.auditTrail);
  const gates=useOfficeStore(s=>s.releaseGates),doctors=useOfficeStore(s=>s.doctorByProject),retention=useOfficeStore(s=>s.retention);
  const gate=gates[state.projectId],doctor=doctors[state.projectId];
  const liveInterrupted=(recovery?.interrupted||[]).filter(x=>["queued","waiting_for_agent","planning","plan_ready","running","verifying"].includes(x.status));
  useWhenOfficeConnected(()=>{send({action:"get_recovery"});send({action:"get_audit"});if(state.projectId!=="none"){send({action:"get_release_gate",project_id:state.projectId});send({action:"get_doctor",project_id:state.projectId});}},[state.projectId]);
  return <section className="hardening-grid">
    <article className="panel"><div className="section-heading"><div><div className="eyebrow">{t("hardening.releaseEyebrow")}</div><h2>{gate?.ready?t("hardening.releaseReady"):t("hardening.releaseNotReady")}</h2></div><button onClick={()=>send({action:"get_release_gate",project_id:state.projectId})}>{t("hardening.refresh")}</button></div><div className="hardening-checks">{gate?.checks.map(c=><div className={c.ok?"ok":"bad"} key={c.id}><i>{c.ok?"✓":"!"}</i><span>{c.label}</span><b>{c.value}</b></div>)}</div></article>
    <article className="panel"><div className="section-heading"><div><div className="eyebrow">{t("hardening.doctorEyebrow")}</div><h2>{doctor?.overall?t(`health.${doctor.overall}`,doctor.overall):t("hardening.checking")}</h2></div><button onClick={()=>send({action:"get_doctor",project_id:state.projectId})}>{t("hardening.doctor")}</button></div><div className="hardening-checks">{doctor?.checks.map(c=><div className={c.status==="pass"?"ok":c.status==="fail"?"bad":"warn"} key={c.id}><i>{c.status==="pass"?"✓":c.status==="fail"?"×":"!"}</i><span>{c.label}</span><b>{c.detail}</b></div>)}</div></article>
    <article className="panel"><div className="section-heading"><div><div className="eyebrow">{t("hardening.recoveryEyebrow")}</div><h2>{t("hardening.recoveryTitle")}</h2></div><button onClick={()=>send({action:"cleanup_recovery"})}>{t("hardening.cleanStale")}</button></div><div className="recovery-stats"><span><b>{liveInterrupted.length}</b> {t("hardening.interrupted")}</span><span><b>{recovery?.staleWorktrees.length??0}</b> {t("hardening.staleWorktrees")}</span><span><b>{recovery?.rollbackRisks.length??0}</b> {t("hardening.rollbackRisks")}</span></div>{liveInterrupted.slice(0,6).map(x=><div className="recovery-row" key={x.id}><strong>{x.title}</strong><span>{x.status}</span><small>{x.message}</small><div className="recovery-actions"><button onClick={()=>send({action:"recover_command",command_id:x.id})}>{t("hardening.resume")}</button><button onClick={()=>send({action:"discard_recovery",command_id:x.id})}>{t("hardening.discard")}</button></div></div>)}</article>
    <article className="panel"><div className="section-heading"><div><div className="eyebrow">{t("hardening.retentionEyebrow")}</div><h2>{t("hardening.retentionTitle")}</h2></div></div><div className="retention-controls"><label>{t("hardening.reportsDays")}<input type="number" value={retention.reportsDays} onChange={e=>send({action:"set_retention",...retention,reportsDays:Number(e.target.value)})}/></label><label>{t("hardening.auditDays")}<input type="number" value={retention.auditDays} onChange={e=>send({action:"set_retention",...retention,auditDays:Number(e.target.value)})}/></label><label>{t("hardening.worktreeDays")}<input type="number" value={retention.worktreeDays} onChange={e=>send({action:"set_retention",...retention,worktreeDays:Number(e.target.value)})}/></label><button onClick={()=>send({action:"run_retention_cleanup"})}>{t("hardening.cleanup")}</button></div></article>
    <article className="panel audit-trail-panel"><div className="section-heading"><div><div className="eyebrow">{t("hardening.auditEyebrow")}</div><h2>{t("hardening.auditTitle")}</h2></div><button onClick={()=>send({action:"get_audit"})}>{t("hardening.refresh")}</button></div><div className="audit-scroll">{audit.filter(x=>x.projectId===state.projectId).slice(0,80).map(x=><div className={`audit-row audit-${x.outcome}`} key={x.id}><time>{new Date(x.timestamp).toLocaleTimeString()}</time><strong>{x.actor}</strong><span>{x.action}</span><p>{x.message}</p></div>)}</div></article>
  </section>;
}
