Write-Host ""
Write-Host "AI Development Office Runner Setup"
Write-Host "=================================="
Write-Host ""
Write-Host "This helper does not install anything automatically."
Write-Host "Run the provider command you want:"
Write-Host ""
Write-Host "Cursor:"
Write-Host "  irm 'https://cursor.com/install?win32=true' | iex"
Write-Host "  agent --version"
Write-Host "  agent login"
Write-Host ""
Write-Host "Claude Code:"
Write-Host "  irm https://claude.ai/install.ps1 | iex"
Write-Host "  claude --version"
Write-Host "  claude doctor"
Write-Host "  claude"
Write-Host ""
Write-Host "After installing/logging in, restart AI Development Office."
